# Generated by Django 5.2.6 on 2025-09-17 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('power', models.FloatField(verbose_name='ضریب')),
            ],
            options={
                'verbose_name': 'واحد اندازه گیری',
                'verbose_name_plural': 'واحد های اندازه گیری',
            },
        ),
        migrations.CreateModel(
            name='RawMaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_categories', to='warehousing.rawmaterialcategory', verbose_name='والد')),
            ],
            options={
                'verbose_name': 'دسته بندی ماده اولیه',
                'verbose_name_plural': 'دسته بندی های ماده اولیه',
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ternal', models.CharField(choices=[('1', 'وارداتی'), ('2', 'داخلی')], max_length=1, verbose_name='نوع')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('amount', models.PositiveIntegerField(verbose_name='مقدار')),
                ('purchase_date', models.CharField(max_length=10, verbose_name='تاریخ خرید')),
                ('arrival_date', models.CharField(max_length=10, verbose_name='تاریخ ورود')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_raw_materials', to='warehousing.rawmaterialcategory', verbose_name='دسته بندی')),
                ('input_unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='input_unit_raw_materials', to='warehousing.unit', verbose_name='واحد ورودی')),
                ('output_unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='output_unit_raw_materials', to='warehousing.unit', verbose_name='واحد خروجی')),
            ],
            options={
                'verbose_name': 'ماده اولیه',
                'verbose_name_plural': 'مواد اولیه',
            },
        ),
    ]
