# Generated by Django 5.2.6 on 2025-09-18 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'تعریف واحد', 'verbose_name_plural': 'تعریف واحد ها'},
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='name',
        ),
        migrations.AlterField(
            model_name='rawmaterialcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_categories', to='warehousing.rawmaterialcategory', verbose_name='والد'),
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='unit_commodity', to='warehousing.unit', verbose_name='واحد')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالا ها',
            },
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='commodity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='commodity_raw_materials', to='warehousing.commodity', verbose_name='کالا'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CommodityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_categories', to='warehousing.commoditycategory', verbose_name='والد')),
            ],
            options={
                'verbose_name': 'دسته بندی کالا',
                'verbose_name_plural': 'دسته بندی های کالا',
            },
        ),
        migrations.AddField(
            model_name='commodity',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_commodities', to='warehousing.commoditycategory', verbose_name='دسته بندی'),
        ),
        migrations.CreateModel(
            name='RawMaterialFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.IntegerField(verbose_name='مقدار تغییر')),
                ('date', models.CharField(max_length=10, verbose_name='تاریخ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات (اختیاری)')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_material_factors', to='warehousing.rawmaterial', verbose_name='ماده اولیه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_raw_material_factors', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'فاکتور ماده اولیه',
                'verbose_name_plural': 'فاکتور های ماده اولیه',
            },
        ),
    ]
