# Generated by Django 5.2.6 on 2025-09-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0002_alter_unit_options_remove_rawmaterial_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rawmaterialfactor',
            options={'verbose_name': 'فاکتور سایت', 'verbose_name_plural': 'فاکتور های سایت'},
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='output_amount',
            field=models.FloatField(default=1, verbose_name='مقدار خروجی (قابل مصرف)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='amount',
            field=models.FloatField(verbose_name='مقدار'),
        ),
    ]
