# Generated by Django 5.2.6 on 2025-09-18 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0003_alter_rawmaterialfactor_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='power',
        ),
    ]
