# Generated by Django 5.2.6 on 2025-09-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0004_remove_unit_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='price',
            field=models.PositiveBigIntegerField(default=1000000, verbose_name='قیمت (ریال)'),
            preserve_default=False,
        ),
    ]
