# Generated by Django 5.2.6 on 2025-09-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0005_rawmaterial_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='supplier',
            field=models.CharField(default='تامین کننده ایکس', max_length=200, verbose_name='تامین کننده'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='amount',
            field=models.FloatField(verbose_name='مقدار ورودی'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='price',
            field=models.PositiveBigIntegerField(verbose_name='قیمت خرید هر واحد (ریال)'),
        ),
    ]
