# Generated by Django 5.2.6 on 2025-09-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0006_rawmaterial_supplier_alter_rawmaterial_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='مقدار ورودی'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='output_amount',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='مقدار خروجی (قابل مصرف)'),
        ),
    ]
