# Generated by Django 5.2.6 on 2025-09-19 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0007_alter_rawmaterial_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('address', models.CharField(max_length=500, verbose_name='آدرس')),
                ('phone_number', models.PositiveBigIntegerField(verbose_name='شماره همراه')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'تامین کننده',
                'verbose_name_plural': 'تامین کنندگان',
            },
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='supplier',
        ),
        migrations.AddField(
            model_name='commodity',
            name='ternal',
            field=models.CharField(choices=[('1', 'وارداتی'), ('2', 'داخلی')], default='1', max_length=1, verbose_name='نوع'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='supplier_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='supplier_raw_materials', to='warehousing.supplier', verbose_name='تامین کننده'),
        ),
    ]
