# Generated by Django 5.2.6 on 2025-09-19 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0008_supplier_remove_rawmaterial_supplier_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawmaterial',
            old_name='supplier_2',
            new_name='supplier',
        ),
    ]
