# Generated by Django 5.2.6 on 2025-09-19 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0009_rename_supplier_2_rawmaterial_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='supplier_raw_materials', to='warehousing.supplier', verbose_name='تامین کننده'),
            preserve_default=False,
        ),
    ]
