# Generated by Django 5.2.6 on 2025-09-19 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0010_alter_rawmaterial_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodity',
            name='ternal',
        ),
        migrations.RemoveField(
            model_name='rawmaterialcategory',
            name='parent',
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='commodity_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='commodity_category_raw_materials', to='warehousing.commoditycategory', verbose_name='دسته بندی کالا'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawmaterialcategory',
            name='ternal',
            field=models.CharField(choices=[('1', 'وارداتی'), ('2', 'داخلی')], default='1', max_length=1, verbose_name='نوع'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commoditycategory',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_categories', to='warehousing.rawmaterialcategory', verbose_name='والد'),
            preserve_default=False,
        ),
    ]
