# Generated by Django 5.2.6 on 2025-09-20 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0011_remove_commodity_ternal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyRawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.PositiveIntegerField(verbose_name='مقدار خرید')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_raw_materials', to='warehousing.rawmaterial', verbose_name='ماده اولیه')),
            ],
        ),
    ]
