# Generated by Django 5.2.6 on 2025-09-20 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0012_buyrawmaterial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RawMaterialFactor',
        ),
    ]
